[package]
name = "ytflow"
version = "0.1.0"
authors = ["bdbai <bdbaiapp@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(windows)'.build-dependencies]
windows = "0.21"

[dependencies]

# Primitive
bitflags = "1"
async-trait = "0.1"
parking_lot = "0.11"
futures = { version = "0.3", default-features = false, features = ["std", "async-await"] }
thiserror = "1"
pin-project-lite = "0.2"
chrono = "*"
replace_with = "0.1"

# Container
flume = { version = "0.10", default-features = false, features = ["async"] }
smallvec = { version = "1", features = ["union", "serde"] }
lru = "0.7"
arc-swap = "1"
cidr = { version = "0.2", features = ["serde"] }

# FFI
libc = "0.2"

# Runtime
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "net", "io-util", "time"] }

# Protocol
httparse = "1"
base64 = "0.13"
getrandom = { version = "0.2", default-features = false, features = ["std"] }
crypto2 = { version = "0.1", default-features = false, features = ["std"] }
trust-dns-resolver = { version = "0.20", default-features = false, features = ["tokio-runtime"] }
# UWP build is only supported since OpenSSL 3.0
openssl = { version = "^0.10.38", features = ["vendored"] }
tokio-openssl = "0.6"

# Data
serde = { version = "1", features = ["derive"] }
refinery = { version = "0.7", features = ["rusqlite"] }
refinery-core = "*"
rusqlite = { version = "*", features = ["chrono", "winsqlite3"] }
libsqlite3-sys = "*"
ciborium = { git = "https://github.com/enarx/ciborium.git" }

[target.'cfg(windows)'.dependencies]
windows = "0.21"
widestring = "0.5"

[dependencies.smoltcp]
git = "https://github.com/smoltcp-rs/smoltcp.git"
default-features = false
features = ["std", "log", "alloc", "medium-ip", "medium-ethernet", "proto-ipv4", "proto-ipv6", "socket-tcp", "socket-udp", "async"]
