[package]
name = "ytflow"
version = "0.1.0"
authors = ["bdbai <bdbaiapp@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Primitive
bitflags = "1"
async-trait = "0.1"
futures = { version = "0.3", default-features = false, features = [
    "std",
    "async-await",
] }
thiserror = "1"
pin-project-lite = "0.2"
chrono = { version = "*", features = ["serde"] }
memchr = "2"
rand = "0.8"
itertools = "0.10"

# Container
flume = { version = "0.10", default-features = false, features = ["async"] }
smallvec = { version = "1", features = ["union", "serde"] }
lru = "0.7"
arc-swap = "1"
cidr = { version = "0.2", features = ["serde"] }

# FFI
libc = "0.2"
socket2 = "0.4"

# Runtime
# To use patched mio v0.7.
tokio = { version = "=1.16.1", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "net",
    "io-util",
    "time",
    "macros",
] }

# Protocol
httparse = "1"
base64 = "0.13"
getrandom = { version = "0.2", default-features = false, features = ["std"] }
crypto2 = { git = "https://github.com/shadowsocks/crypto2.git", default-features = false, features = [
    "std",
] }
trust-dns-resolver = { version = "0.20", default-features = false, features = [
    "tokio-runtime",
] }
# Note: UWP build is only supported since OpenSSL 3.0
openssl = "0.10"
tokio-openssl = "0.6"

# Data
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
refinery = { version = "0.8", features = ["rusqlite"] }
refinery-core = "0.8"
cbor4ii = { version = "0.2", features = ["use_std", "serde1-value"] }

[target.'cfg(windows)'.dependencies]
rusqlite = { version = "0.26", features = ["chrono", "winsqlite3"] }
windows = { version = "0.28", features = ["alloc", "std"] }
ipconfig = { git = "https://github.com/liranringel/ipconfig.git", default-features = false }

[target.'cfg(windows)'.build-dependencies]
windows = { version = "0.28", features = ["alloc", "std", "build"] }

[target.'cfg(not(windows))'.dependencies]
rusqlite = { version = "0.26", features = ["chrono"] }

[target.'cfg(target_os = "linux")'.dependencies]
rtnetlink = "0.8"
netlink-packet-route = "*"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
fruity = { version = "0.3", features = [
    "foundation",
    "core_foundation",
    "dispatch",
] }
nix = { version = "0.26", default-features = false, features = ["net"] }
block2 = "=0.2.0-alpha.6"

[dependencies.smoltcp]
version = "0.8"
default-features = false
features = [
    "std",
    "log",
    "alloc",
    "medium-ip",
    "medium-ethernet",
    "proto-ipv4",
    "proto-ipv6",
    "socket-tcp",
    "socket-udp",
    "async",
]
