[package]
name = "ytflow"
version = "0.1.0"
authors = ["bdbai <bdbaiapp@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Primitive
bitflags = "1"
async-trait = "0.1"
parking_lot = "0.11"
futures = { version = "0.3", default-features = false, features = ["std", "async-await"] }
thiserror = "1"
pin-project-lite = "0.2"
chrono = { version = "*", features = ["serde"] }

# Container
flume = { version = "0.10", default-features = false, features = ["async"] }
smallvec = { version = "1", features = ["union", "serde"] }
lru = "0.7"
arc-swap = "1"
cidr = { version = "0.2", features = ["serde"] }

# FFI
libc = "0.2"

# Runtime
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "net", "io-util", "time"] }

# Protocol
httparse = "1"
base64 = "0.13"
getrandom = { version = "0.2", default-features = false, features = ["std"] }
crypto2 = { version = "0.1", default-features = false, features = ["std"] }
trust-dns-resolver = { version = "0.20", default-features = false, features = ["tokio-runtime"] }
tokio-openssl = "0.6"

# Data
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
refinery = { version = "0.7", features = ["rusqlite"] }
refinery-core = "*"
cbor4ii = { version = "0.2", features = ["use_std", "serde1-value"] }

[target.'cfg(windows)'.dependencies]
# UWP build is only supported since OpenSSL 3.0
openssl = { version = "^0.10.38", features = ["vendored"] }
openssl-sys = "=0.9.71"
rusqlite = { version = "*", features = ["chrono", "winsqlite3"] }
windows = { version = "0.28", features = ["alloc", "std"] }
ipconfig = { git = "https://github.com/YtFlow/ipconfig.git", default-features = false, branch = "feat/uwp" }

[target.'cfg(windows)'.build-dependencies]
windows = { version = "0.28", features = ["alloc", "std", "build"] }

[target.'cfg(not(windows))'.dependencies]
openssl = "0.10"
rusqlite = { version = "*", features = ["chrono"] }

[target.'cfg(target_os = "linux")'.dependencies]
rtnetlink = "0.8"
netlink-packet-route = "*"

[dependencies.smoltcp]
version = "0.8"
default-features = false
features = ["std", "log", "alloc", "medium-ip", "medium-ethernet", "proto-ipv4", "proto-ipv6", "socket-tcp", "socket-udp", "async"]
