[workspace]
members = [
    "ytflow",
    "ytflow-bin",
    "ytflow-ffi",
    "ytflow-uwp-plugin",
]

[patch.crates-io]
mio = { git = "https://github.com/YtFlow/mio-noafd" }

[profile.release]
lto = true
codegen-units = 1
