namespace = "ytflow_core"
pragma_once = true
after_includes = "namespace ytflow_core { struct Connection; }"

[parse]
parse_deps = true
include = ["ytflow"]
extra_bindings = ["ytflow"]

[defines]
"windows" = "_WIN32"
"unix" = "__unix__"

[export.mangle]
rename_types = "SnakeCase"
