name: Run Build and Tests

on:
  push:
    branches: [ main, ci-scratch ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-bin:

    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Prepare toolchain
      run: rustup show
    - uses: Swatinem/rust-cache@v1

    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test

  build-uwp:
  
    runs-on: windows-latest
    env:
      UWP_TARGET_TRIPLET: thumbv7a-uwp-windows-msvc
      BUILD_STD_ARGS: build-std=std,panic_abort
    
    steps:
    - uses: actions/checkout@v2
    - name: Prepare toolchain
      run: rustup show
    - uses: Swatinem/rust-cache@v1

    - name: Build
      run: cargo build -p ytflow-uwp-plugin -Z $env:BUILD_STD_ARGS --target $env:UWP_TARGET_TRIPLET
    - name: Run tests
      run: |
        cargo test -p ytflow -Z $env:BUILD_STD_ARGS --target $env:UWP_TARGET_TRIPLET
        cargo test -p ytflow-uwp-plugin -Z $env:BUILD_STD_ARGS --target $env:UWP_TARGET_TRIPLET
